name: Node.js gimme data

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} npm run api
